apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currency-converter-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: currency-converter
    environment: production
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/abdulrahman11a/argocd-demo
    targetRevision: main
    path: apps/production-app/
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 10
