apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/abdulrahman11a/argocd-demo.git
    targetRevision: main
    path: overlays/production 

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
